# (Gridsearch) 00 GRU trefor park

In [46]:
import torch
from core.util.hyperparameter_configuration import get_hyperparameter_configuration
from core.util.get_datasets import cross_validation
from core.models.model_training import train_model
from sklearn.model_selection import ParameterGrid
from core.util.save_model import save_parameters, load_parameters
from core.util.trefor_dataset import TreforData
from torch.utils.data import DataLoader
from core.models import GRU

## Configuration
Parameters specific to this experiment

In [47]:
experiment_name = "00_GRU_trefor_park"
features = {}
model_input_size = len(features) + 1
model_used = GRU

All the paramaters we do grid search on

In [48]:
gridsearch_params = {
    "learning_rate": [0.001, 0.003, 0.005],
    "batch_size": [32, 64, 128],
    "lookback": [36, 48, 96],
    "num_layers": [1, 2],
    "seed": [1, 2, 3, 4, 21121219],
}

In [49]:
hyperparameters = get_hyperparameter_configuration()
hidden_size = hyperparameters["hidden_size"]
epochs = hyperparameters["epochs"]
horizon = hyperparameters["horizon"]
loss_function = hyperparameters["loss_function"]
dropout_rate = hyperparameters["dropout_rate"]
train_days = hyperparameters["train_days"]
val_days = hyperparameters["val_days"]
test_days = hyperparameters["test_days"]
early_stopper = hyperparameters["early_stopper"]

hyperparameters

{'hidden_size': 16,
 'epochs': 200,
 'horizon': 24,
 'loss_function': <function core.util.loss_functions.zap_loss(y_pred: torch.Tensor, y_true: torch.Tensor) -> torch.Tensor>,
 'dropout_rate': 0.2,
 'train_days': 224,
 'val_days': 28,
 'test_days': 28,
 'early_stopper': <core.util.early_stop.EarlyStop at 0x1552ee1e0>}

Use CUDA (GPU) if available.

In [50]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

## Training
Train a model with specified hyperparameters

In [51]:
def train_with_params(params: dict) -> tuple[float, model_used]:
    """Train model with the specified hyperparameters."""
    # Extract hyperparameters
    batch_size = params["batch_size"]
    learning_rate = params["learning_rate"]
    num_layers = params["num_layers"]
    lookback = params["lookback"]
    torch.manual_seed(params["seed"])

    x_train, y_train, x_val, y_val, x_test, y_test = cross_validation(
        lookback=lookback,
        horizon=horizon,
        train_days=train_days,
        val_days=val_days,
        test_days=test_days,
        features={},
    )

    # convert to dataset that can use dataloaders
    train_dataset = TreforData(x_train, y_train, device)
    val_dataset = TreforData(x_val, y_val, device)

    # initialize the dataloaders, without shuffeling the data between epochs
    training_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
    validation_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    # Initialize model
    model = model_used(
        input_size=model_input_size,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout_rate=dropout_rate,
        horizon=horizon,
        lookback=lookback,
    ).to(device)

    _, val_loss, best_model = train_model(
        epochs=epochs,
        model=model,
        loss_function=loss_function,
        training_loader=training_loader,
        validation_loader=validation_loader,
        learning_rate=learning_rate,
        early_stopper=early_stopper,
    )

    return min(val_loss), best_model

Iterate over all hyperparameters and train a model for each combination.

In [ ]:
best_loss = float("inf")
best_params = None
best_model = None

for params in ParameterGrid(gridsearch_params):
    early_stopper.reset()
    v_loss, model = train_with_params(params)
    print(params, v_loss)
    if v_loss < best_loss:
        best_loss = v_loss
        best_params = params
        best_model = model

save_parameters(experiment_name, best_params, best_loss)
print("Best Hyperparameters:", best_params)
print("Best Validation Loss:", best_loss)

[[7.50000000e-07]
 [4.95625000e-04]
 [3.71377500e-02]
 ...
 [2.60611375e-01]
 [1.77827500e-02]
 [2.72323750e-02]]
[[0.0237646 ]
 [0.00148804]
 [0.0024376 ]
 ...
 [0.053728  ]
 [0.024952  ]
 [0.0248    ]]
[[0.00221575]
 [0.0022122 ]
 [0.00220915]
 ...
 [0.1526433 ]
 [0.0351757 ]
 [0.00992975]]
[[0.00229313]
 [0.00229637]
 [0.00230825]
 ...
 [0.01023087]
 [0.00980025]
 [0.0096555 ]]
[[0.00109511]
 [0.00087289]
 [0.000873  ]
 ...
 [0.13800411]
 [0.00200189]
 [0.00200189]]
[[0.03242462]
 [0.00219985]
 [0.00219892]
 ...
 [0.04218746]
 [0.00256946]
 [0.00257823]]


Iterating epochs:   0%|          | 0/200 [00:00<?, ?it/s]